// ─────────────────────────────────────────────────────────────────────────────
// DEMO CONTENT: ILLUSTRATIVE CONCEPTS ONLY.
// Nothing here is a real client, project, result or date. Each is an original drawing,
// not a photograph. Delete this folder and set SHOW_DEMO_CONTENT to false in ../index.ts
// before launch. Real, approved projects belong in ../projects.ts.
// ─────────────────────────────────────────────────────────────────────────────
import type { Project } from "../types";

const base = { status: "concept" as const, isDemo: true, outcomes: [] as string[], media: [] as Project["media"] };

export const demoProjects: Project[] = [
  {
    ...base,
    slug: "concept-courtyard-lounge",
    title: "Courtyard lounge",
    service: "interiors",
    ratio: "landscape",
    summary: "A residential lounge organised around one arched opening to a courtyard.",
    overview: "A concept for a family lounge where a single arch frames the garden and the joinery does the rest.",
    brief: "A lounge that is calm in the day and warm in the evening, with storage that disappears into the walls.",
    response: "One arched opening frames the courtyard. Battened joinery runs along the side walls in a single tone, so the eye rests on the opening and the light beyond it.",
    materials: ["lacquer", "plaster", "terrazzo", "brass"],
    development: "The battened wall is drawn as a section first: batten width, gap and backing decide both the look and how the panel is fixed.",
    execution: "A real project page would describe fabrication, fixings and the site programme here.",
    plate: "interior",
    drawings: [
      { fragment: "plan-interior", caption: "Concept plan: lounge, arch and courtyard axis." },
      { fragment: "joinery-section", caption: "Section through the battened wall." },
    ],
  },
  {
    ...base,
    slug: "concept-hall-stand",
    title: "Two-storey corner stand",
    service: "exhibitions",
    ratio: "portrait",
    summary: "A corner stand with an open ground floor and a quiet meeting level above.",
    overview: "A concept for a corner stand that draws visitors in from two aisles and keeps meetings above the noise.",
    brief: "A stand that invites people off a busy aisle and gives private conversations somewhere to happen.",
    response: "Two open sides meet the aisles. A tall fascia signals the stand from down the hall, and meetings move to a level above.",
    materials: ["lacquer", "felt", "coral-paint", "ply"],
    development: "The structure is drawn as a demountable frame so it can be shipped flat and assembled in the build window.",
    execution: "A real project page would cover shipping, install nights and dismantle.",
    plate: "stand",
    drawings: [
      { fragment: "plan-stand", caption: "Plan: two open sides, reception and meeting stair." },
      { fragment: "kit", caption: "Demountable frame, exploded." },
    ],
  },
  {
    ...base,
    slug: "concept-launch-stage",
    title: "Launch stage",
    service: "events",
    ratio: "landscape",
    summary: "One reveal moment, staged to be seen from every seat.",
    overview: "A concept for a product reveal in a room for four hundred.",
    brief: "One moment the whole room should see, with a fast load-in.",
    response: "A raised plinth sits inside a simple truss frame. Everything around it stays quiet so the reveal lands.",
    materials: ["lacquer", "felt", "coral-paint", "ply"],
    development: "A section checks sightlines from the front row to the back of the raked seating.",
    execution: "A real project page would cover rigging, load-in and show support.",
    plate: "stage",
    drawings: [
      { fragment: "section-stage", caption: "Section: stage, truss and raked seating." },
      { fragment: "kit", caption: "Set pieces, exploded for load-in." },
    ],
  },
  {
    ...base,
    slug: "concept-corner-popup",
    title: "Modular pop-up",
    service: "brand-activations",
    ratio: "square",
    summary: "A small modular pop-up that opens on two sides and can be rebuilt elsewhere.",
    overview: "A concept for a pop-up designed to be rebuilt in a mall atrium, a street market and a hotel lobby.",
    brief: "A pop-up that can move between very different sites without being redesigned each time.",
    response: "Four identical modules lock together. A striped canopy gives a recognisable roofline wherever it lands.",
    materials: ["ply", "coral-paint", "felt", "brass"],
    development: "Modules are drawn to fit a standard vehicle, with a one-page assembly sequence.",
    execution: "A real project page would cover transport, rebuild time and servicing.",
    plate: "popup",
    drawings: [
      { fragment: "kit", caption: "Kit of parts, exploded." },
      { fragment: "plan-stand", caption: "Plan: two open sides and a counter." },
    ],
  },
  {
    ...base,
    slug: "concept-sliding-window",
    title: "Sliding panel window",
    service: "kinetic-windows",
    ratio: "portrait",
    summary: "A retail window where panels slowly rearrange a scene on rails.",
    overview: "A concept for a window that changes as people walk past, with one full cycle of about fourteen seconds.",
    brief: "A shopfront window with a repeating movement that a passer-by can read in one glance.",
    response: "Two panels slide on overhead rails while a pendant disc rises and swings. The mechanism is visible, quiet and serviceable.",
    materials: ["brass", "lacquer", "coral-paint", "felt"],
    development: "The rails, carriages and drive are drawn with service access from behind the glass.",
    execution: "A real project page would cover workshop testing, after-hours installation and servicing.",
    plate: "window",
    drawings: [
      { fragment: "rail-elevation", caption: "Elevation: rails, carriages and panels." },
      { fragment: "joinery-section", caption: "Section through a panel and its carriage." },
    ],
  },
  {
    ...base,
    slug: "concept-garden-villa",
    title: "Villa entrance hall",
    service: "interiors",
    ratio: "landscape",
    summary: "An entrance hall that moves from courtyard light to a warmer interior.",
    overview: "A concept for an entrance that feels generous without adding square metres.",
    brief: "An arrival that introduces the house: light, a place to sit and a view through.",
    response: "A long bench, a pendant and a planter stage the arrival. A single brass inlay in the terrazzo leads the eye to the arch.",
    materials: ["terrazzo", "plaster", "brass", "travertine"],
    development: "The terrazzo layout is drawn with movement joints so the brass inlay sits on a joint line.",
    execution: "A real project page would cover sequencing with the trades and finishes.",
    plate: "villa",
    drawings: [
      { fragment: "plan-interior", caption: "Plan: entrance, bench and courtyard view." },
      { fragment: "joinery-section", caption: "Section through the bench and wall." },
    ],
  },
];
