// Generated by scripts/build-portfolio.py from the studio company profile PDF. Facts and labels are as printed there.
import type { ServiceSlug } from "./types";

export type Category = "events" | "exhibitions" | "brand-activations" | "kinetic-windows" | "retail" | "commercial" | "residential" | "food-and-beverage";
export type PortfolioImage = { src: string; thumb: string; w: number; h: number };
export type PortfolioProject = {
  slug: string; title: string; client: string; category: Category; service: ServiceSlug;
  /** The status label exactly as the studio's profile prints it (for example Concept design, Design & build). Empty when none is printed. */
  label: string; where: string; year: number | null; summary: string; paragraphs: string[]; images: PortfolioImage[]; alt: string;
};

export const CATEGORIES: { id: Category; name: string }[] = [
  { id: "events", name: "Events" }, { id: "exhibitions", name: "Exhibitions" }, { id: "brand-activations", name: "Brand activations" },
  { id: "kinetic-windows", name: "Kinetic windows" }, { id: "retail", name: "Retail" }, { id: "commercial", name: "Commercial" },
  { id: "residential", name: "Residential" }, { id: "food-and-beverage", name: "Food and beverage" },
];

export const PORTFOLIO: PortfolioProject[] = [
  { slug: "ahmed-al-maghribi-launch", title: "Ahmed Al Maghribi brand launch", client: "Ahmed Al Maghribi", category: "events", service: "events", label: "Concept, design, build, hamper curation and event management", where: "Armani Hotel terrace, Burj Khalifa, Dubai", year: 2025,
    summary: "A full-scale perfume launch at the outdoor terrace of Armani Hotel, Burj Khalifa.",
    paragraphs: [
      "A full-scale perfume launch at the outdoor terrace of Armani Hotel, Burj Khalifa. Concept rooted in a movie premiere narrative — tracing the founder’s personal journey through scent, heritage and vision. Guests arrived through a custom-built premiere entrance arch.",
      "The journey opened into a souk-inspired zone referencing traditional Arabian perfumery, complete with a live bukhoor bar-making experience for guests. A 10-metre immersive tunnel marked the transition Live calligraphers lining its length, hand-writing guest names on fans, with perfume display carts positioned throughout for an intimate encounter with the collection.",
      "The outdoor gala space was anchored by a 4m × 9m LED screen with formal gala tables set for the three-bottle reveal the centrepiece moment of the evening. Post-reveal, guests moved into three individually designed experiential zones Past, Present and Future — each distinct in material palette, finish language and atmosphere."
    ],
    images: [{"src": "/work/ahmed-al-maghribi-launch/01.webp", "thumb": "/work/ahmed-al-maghribi-launch/01-sm.webp", "w": 882, "h": 1204}, {"src": "/work/ahmed-al-maghribi-launch/02.webp", "thumb": "/work/ahmed-al-maghribi-launch/02-sm.webp", "w": 620, "h": 901}, {"src": "/work/ahmed-al-maghribi-launch/03.webp", "thumb": "/work/ahmed-al-maghribi-launch/03-sm.webp", "w": 1165, "h": 694}, {"src": "/work/ahmed-al-maghribi-launch/04.webp", "thumb": "/work/ahmed-al-maghribi-launch/04-sm.webp", "w": 1425, "h": 787}, {"src": "/work/ahmed-al-maghribi-launch/05.webp", "thumb": "/work/ahmed-al-maghribi-launch/05-sm.webp", "w": 748, "h": 367}, {"src": "/work/ahmed-al-maghribi-launch/06.webp", "thumb": "/work/ahmed-al-maghribi-launch/06-sm.webp", "w": 546, "h": 901}, {"src": "/work/ahmed-al-maghribi-launch/07.webp", "thumb": "/work/ahmed-al-maghribi-launch/07-sm.webp", "w": 749, "h": 419}], alt: "Perfume launch event" },
  { slug: "laduree-ramadan-tent", title: "Ladurée Ramadan tent", client: "Ladurée", category: "events", service: "events", label: "Design & build", where: "Al Bateen Marina", year: 2025,
    summary: "A Ramadan tent that blends Parisian elegance with Middle Eastern tradition on the Al Bateen waterfront.",
    paragraphs: [
      "Ladurée Al Bateen Ramadan Tent blends Parisian elegance with Middle Eastern tradition. The waterfront terrace was transformed into a stylish modern Majlis, offering an intimate setting by the serene Al Bateen Marina. A tent structure measuring 8 x 15 meters forms the centerpiece of the setup, draped in Ladurée’s signature beige fabric to evoke a warm and inviting Middle Eastern ambiance.",
      "To complement the luxurious atmosphere, three custom-designed foldable live cooking stations were introduced, elegantly showcasing an array of desserts and traditional Suhoor dishes. These stations were crafted to reflect Ladurée’s brand guidelines, seamlessly integrating into the space while enhancing the overall sensory experience of the evening."
    ],
    images: [{"src": "/work/laduree-ramadan-tent/01.webp", "thumb": "/work/laduree-ramadan-tent/01-sm.webp", "w": 509, "h": 287}, {"src": "/work/laduree-ramadan-tent/02.webp", "thumb": "/work/laduree-ramadan-tent/02-sm.webp", "w": 300, "h": 198}, {"src": "/work/laduree-ramadan-tent/03.webp", "thumb": "/work/laduree-ramadan-tent/03-sm.webp", "w": 553, "h": 385}], alt: "Ramadan tent" },
  { slug: "al-haramain-beauty-world", title: "Al Haramain exhibition stand", client: "Al Haramain", category: "exhibitions", service: "exhibitions", label: "Concept design", where: "Beauty World Middle East", year: 2025,
    summary: "A large-format exhibition stand concept for Al Haramain, one of the region’s most iconic fragrance houses.",
    paragraphs: [
      "A large-format exhibition stand concept for Al Haramain, one of the region’s most iconic fragrance houses. The stand was designed as four distinct experience zones wrapping a central cylindrical tower each side of the stand offering a different activation: a personalised perfume bottle engraving station, a perfume spray dispenser experience, a dedicated fragrance display zone and a private lounge for trade and VIP guests.",
      "A curved LED screen anchored the entrance façade, wrapping campaign imagery around the corner in a seamless flow of gold and amber. A key design consideration was longevity the shelving and display units were conceived to be fully demountable and reusable, transitioning directly from the exhibition floor into Al Haramain’s permanent showroom environment after the event.",
      "Form following function, without compromising either."
    ],
    images: [{"src": "/work/al-haramain-beauty-world/01.webp", "thumb": "/work/al-haramain-beauty-world/01-sm.webp", "w": 1435, "h": 797}, {"src": "/work/al-haramain-beauty-world/02.webp", "thumb": "/work/al-haramain-beauty-world/02-sm.webp", "w": 1435, "h": 787}, {"src": "/work/al-haramain-beauty-world/03.webp", "thumb": "/work/al-haramain-beauty-world/03-sm.webp", "w": 1148, "h": 691}], alt: "Exhibition stand" },
  { slug: "laduree-expex", title: "Ladurée exhibition stand", client: "Ladurée", category: "exhibitions", service: "exhibitions", label: "Concept design", where: "EXPEX", year: 2025,
    summary: "A Parisian patisserie brought to the exhibition floor.",
    paragraphs: [
      "A Parisian patisserie brought to the exhibition floor. Ladurée is synonymous with more than retail their world extends to private events, gifting and bespoke experiences, and the stand had to communicate all of it. Designed and built in Ladurée’s signature sage green, gold and soft pastels, the space balanced product retail with event hospitality a vintage cart as the hero centrepiece, gilded macaron display frames on a bloom-draped floral wall, deep green awnings, a warmly lit shelving wall for gift collections and a branded service counter for guest engagement.",
      "A space that spoke equally to a walk-in customer and a private event client feeling less like an exhibition booth and more like a stroll down Rue Royale."
    ],
    images: [{"src": "/work/laduree-expex/01.webp", "thumb": "/work/laduree-expex/01-sm.webp", "w": 1425, "h": 789}, {"src": "/work/laduree-expex/02.webp", "thumb": "/work/laduree-expex/02-sm.webp", "w": 1426, "h": 804}, {"src": "/work/laduree-expex/03.webp", "thumb": "/work/laduree-expex/03-sm.webp", "w": 1165, "h": 900}, {"src": "/work/laduree-expex/04.webp", "thumb": "/work/laduree-expex/04-sm.webp", "w": 1174, "h": 695}, {"src": "/work/laduree-expex/05.webp", "thumb": "/work/laduree-expex/05-sm.webp", "w": 1148, "h": 900}], alt: "Exhibition stand" },
  { slug: "aj-steel-pipes-adipec", title: "AJ Steel Pipes exhibition stand", client: "AJ Steel Pipes", category: "exhibitions", service: "exhibitions", label: "Concept design", where: "ADIPEC, Abu Dhabi", year: 2025,
    summary: "A double-storey exhibition stand concept pitched for AJ Steel Pipes at ADIPEC 2025.",
    paragraphs: [
      "A double-storey exhibition stand concept pitched for AJ Steel Pipes at ADIPEC 2025. The structure balanced industrial credibility with premium brand presence — a curved LED wall spanning the full fascia, a timber-slatted cylindrical brand tower in warm gold and dark grey anchoring the corner, and a hero product display podium showcasing the steel pipe range with lit frame detailing.",
      "The ground floor housed an open visitor engagement zone with lounge seating, while the mezzanine level provided a private meeting room."
    ],
    images: [{"src": "/work/aj-steel-pipes-adipec/01.webp", "thumb": "/work/aj-steel-pipes-adipec/01-sm.webp", "w": 1425, "h": 797}, {"src": "/work/aj-steel-pipes-adipec/02.webp", "thumb": "/work/aj-steel-pipes-adipec/02-sm.webp", "w": 1425, "h": 798}], alt: "Exhibition stand" },
  { slug: "stanley-automechanika", title: "Stanley exhibition stand", client: "Stanley", category: "exhibitions", service: "exhibitions", label: "Concept design", where: "Automechanika Dubai", year: 2025,
    summary: "A large-format stand concept balancing brand visibility with visitor experience.",
    paragraphs: [
      "A large-format exhibition stand concept for GMT, designed for one of the automotive industry’s most prominent regional platforms. The stand balanced brand visibility with visitor experience a bold illuminated LED tower anchoring the product display wall, showcasing the lubricants range in full, with a living green wall adding warmth to the industrial setting.",
      "The centrepiece was a curved timber-clad hospitality pod with a private meeting room, coffee zone and lounge seating designed to host trade conversations as comfortably as it attracted footfall. A feature bonsai, digital kiosks and car imagery across the fascia completed a stand that felt as premium as the product it represented."
    ],
    images: [{"src": "/work/stanley-automechanika/01.webp", "thumb": "/work/stanley-automechanika/01-sm.webp", "w": 1426, "h": 800}, {"src": "/work/stanley-automechanika/02.webp", "thumb": "/work/stanley-automechanika/02-sm.webp", "w": 1426, "h": 794}], alt: "Exhibition stand" },
  { slug: "fifa-arab-cup-qatar", title: "FIFA Arab Cup Qatar", client: "FIFA Arab Cup Qatar 2025", category: "brand-activations", service: "brand-activations", label: "Concept, design & build", where: "Qatar, multi-location rollout", year: 2025,
    summary: "A walk-through activation delivered across multiple high-footfall locations in Qatar.",
    paragraphs: [
      "A large-scale brand activation delivered simultaneously across multiple high-footfall locations throughout Qatar for the FIFA Arab Cup 2025. The installation centred around a bold walk-through structure built in the tournament’s signature red a branded entrance arch flanked by full-height LED columns displaying live match imagery and player visuals.",
      "Inside, an interactive information counter with tournament branding and digital screens created an engagement hub for visitors. A freestanding welcome pavilion with oversized graphics, checkered detailing and the tournament’s Arabic calligraphy identity completed the footprint.",
      "Designed, built and replicated across key retail and public destinations simultaneously bringing the energy of the Arab Cup directly to fans wherever they were in the country."
    ],
    images: [{"src": "/work/fifa-arab-cup-qatar/01.webp", "thumb": "/work/fifa-arab-cup-qatar/01-sm.webp", "w": 1425, "h": 814}, {"src": "/work/fifa-arab-cup-qatar/02.webp", "thumb": "/work/fifa-arab-cup-qatar/02-sm.webp", "w": 1206, "h": 900}, {"src": "/work/fifa-arab-cup-qatar/03.webp", "thumb": "/work/fifa-arab-cup-qatar/03-sm.webp", "w": 1206, "h": 695}, {"src": "/work/fifa-arab-cup-qatar/04.webp", "thumb": "/work/fifa-arab-cup-qatar/04-sm.webp", "w": 934, "h": 524}, {"src": "/work/fifa-arab-cup-qatar/05.webp", "thumb": "/work/fifa-arab-cup-qatar/05-sm.webp", "w": 1425, "h": 793}, {"src": "/work/fifa-arab-cup-qatar/06.webp", "thumb": "/work/fifa-arab-cup-qatar/06-sm.webp", "w": 1043, "h": 1476}], alt: "Brand activation" },
  { slug: "ariel-platinum-gel", title: "Ariel Platinum Gel", client: "Ariel", category: "brand-activations", service: "brand-activations", label: "Concept design", where: "", year: null,
    summary: "A gamified activation built around Ariel’s core promise: stain removal in one wash.",
    paragraphs: [
      "A gamified brand activation built around Ariel’s core promise stain removal in one wash. Shoppers step up to shoot stain balls at a large illuminated screen with four target holes; a successful hit drops a stained cloth behind the screen. The player then pulls a lever, triggering the oversized Ariel bottle to rotate on its axis bubbles rise, and as they do, a motor-driven mechanism rolls the cloth back up clean.",
      "Product messaging, scoring displays and a giant bottle hero prop complete the installation, turning a detergent claim into a hands-on moment shoppers actually remember."
    ],
    images: [{"src": "/work/ariel-platinum-gel/01.webp", "thumb": "/work/ariel-platinum-gel/01-sm.webp", "w": 1426, "h": 814}, {"src": "/work/ariel-platinum-gel/02.webp", "thumb": "/work/ariel-platinum-gel/02-sm.webp", "w": 1425, "h": 792}], alt: "Gamified brand activation" },
  { slug: "huda-beauty-bowling", title: "Huda Beauty bowling alley", client: "Huda Beauty", category: "brand-activations", service: "brand-activations", label: "Concept design", where: "", year: null,
    summary: "A gamified retail activation concept built around Huda Beauty’s Blush Filter Liquid Blush range.",
    paragraphs: [
      "A gamified retail activation concept built around Huda Beauty’s Blush Filter Liquid Blush range. Two bowling lanes in Huda’s signature magenta and blush pink invite players to roll branded balls down the alley, knocking down Blush Filter product bottles set up as pins.",
      "A full strike lights up the iconic BOWL arch in gold, triggering a celebratory moment. The Huda Beauty mascot sits atop the structure, arms raised equal parts cheerleader and brand icon. Playful, product-forward and completely on-brand, the concept turns a product launch into a game nobody wants to stop playing."
    ],
    images: [{"src": "/work/huda-beauty-bowling/01.webp", "thumb": "/work/huda-beauty-bowling/01-sm.webp", "w": 1426, "h": 814}, {"src": "/work/huda-beauty-bowling/02.webp", "thumb": "/work/huda-beauty-bowling/02-sm.webp", "w": 1425, "h": 792}], alt: "Brand activation" },
  { slug: "chopard-kinetic-windows", title: "Chopard kinetic window displays", client: "Chopard", category: "kinetic-windows", service: "kinetic-windows", label: "Concept design", where: "", year: null,
    summary: "Three window concepts where each display moves around a single hero piece.",
    paragraphs: [
      "Window 01— Alpine Eagle | Timepieces The watch dial’s blue feathers become a vibrating kinetic backdrop. Golden fins spiral outward, opening and closing like watch hands. One watch. Everything in service of it.",
      "Window 02 — Diamond Facets | Fine Jewellery Inspired by the multifaceted brilliance of Chopard’s diamond jewellery line, the window is clad entirely in origami-like panels of cream and gold each facet catching light differently as they shift and move. A single hero piece sits centre stage on a marble plinth.",
      "Window 03 — Ice Cube | Jewellery Collection A direct translation of Ice Cube’s signature square facets into spatial design. Backlit geometric modules line the walls, moving in and out in a rhythmic pulse the architecture of ice brought to life. Navy jewellery boxes orbit a central necklace bust on a circular track, each piece emerging and receding like light refracting through a block of ice. Urban elegance meeting kinetic precision."
    ],
    images: [{"src": "/work/chopard-kinetic-windows/01.webp", "thumb": "/work/chopard-kinetic-windows/01-sm.webp", "w": 1425, "h": 1000}, {"src": "/work/chopard-kinetic-windows/02.webp", "thumb": "/work/chopard-kinetic-windows/02-sm.webp", "w": 700, "h": 595}, {"src": "/work/chopard-kinetic-windows/03.webp", "thumb": "/work/chopard-kinetic-windows/03-sm.webp", "w": 714, "h": 595}], alt: "Kinetic window display" },
  { slug: "laduree-snow-globe", title: "Ladurée Christmas snow globe", client: "Ladurée", category: "brand-activations", service: "brand-activations", label: "Concept design", where: "Dubai Hills Mall", year: 2025,
    summary: "A giant snow globe installation conceived for Ladurée’s Christmas activation.",
    paragraphs: [
      "A giant snow globe installation conceived for Ladurée’s Christmas activation. Placed directly outside the Ladurée store, the oversized globe on a sage green and gold branded plinth contains an entire Parisian winter world a gold macaron Ferris wheel turning slowly, a green locomotive carrying macarons circling the base, a Christmas tree built entirely from stacked macarons, and snow falling continuously within the globe.",
      "Every element replaced a traditional Christmas motif with a Ladurée one baubles become macarons, the tree becomes a patisserie tower, the festive train carries confections instead of gifts. A concept that needed no explanation just a stopped shopper and a smile"
    ],
    images: [{"src": "/work/laduree-snow-globe/01.webp", "thumb": "/work/laduree-snow-globe/01-sm.webp", "w": 1006, "h": 1128}, {"src": "/work/laduree-snow-globe/02.webp", "thumb": "/work/laduree-snow-globe/02-sm.webp", "w": 796, "h": 952}], alt: "Christmas brand activation" },
  { slug: "the-juice-beauty", title: "The Juice Beauty", client: "The Juice Beauty", category: "retail", service: "interiors", label: "Concept design", where: "Dubai, mall retail environment", year: null,
    summary: "A retail interior concept developed for a beauty brand, designed around the tension between clinical cleanliness and sensory warmth.",
    paragraphs: [
      "A retail interior concept developed for a beauty brand, designed around the tension between clinical cleanliness and sensory warmth. Bold magenta brand walls anchor the entrance against a terrazzo reception counter, while warm timber slatted shelving and soft arched detailing carry the interior into approachable luxury.",
      "Display plinths in tinted acrylic and terrazzo create a layered product journey from storefront to the back wall drawing the eye in before the customer steps through the door."
    ],
    images: [{"src": "/work/the-juice-beauty/01.webp", "thumb": "/work/the-juice-beauty/01-sm.webp", "w": 1800, "h": 1124}, {"src": "/work/the-juice-beauty/02.webp", "thumb": "/work/the-juice-beauty/02-sm.webp", "w": 1425, "h": 801}, {"src": "/work/the-juice-beauty/03.webp", "thumb": "/work/the-juice-beauty/03-sm.webp", "w": 1426, "h": 789}, {"src": "/work/the-juice-beauty/04.webp", "thumb": "/work/the-juice-beauty/04-sm.webp", "w": 918, "h": 526}], alt: "Retail concept" },
  { slug: "laduree-dubai-hills", title: "Ladurée store renovation", client: "Ladurée", category: "retail", service: "interiors", label: "Design & build", where: "Dubai Hills Mall", year: null,
    summary: "A full renovation proposal and build for the Ladurée branch at Dubai Hills Mall.",
    paragraphs: [
      "A full renovation proposal and build for the Ladurée branch at Dubai Hills Mall. The scope covered both the store facade and the outdoor terrace refreshing the brand’s Parisian identity while enhancing the overall customer experience. Works included an updated window display with new awnings and signage, joinery additions, a new branded ice cream cart positioned at the entrance, and a digital menu update.",
      "The outdoor seating area was redesigned with a signature green perimeter planter border, floral landscaping, a decorative arch entrance and refined furniture transforming the terrace into a garden dining destination as recognisable as the brand itself."
    ],
    images: [{"src": "/work/laduree-dubai-hills/01.webp", "thumb": "/work/laduree-dubai-hills/01-sm.webp", "w": 1800, "h": 1242}, {"src": "/work/laduree-dubai-hills/02.webp", "thumb": "/work/laduree-dubai-hills/02-sm.webp", "w": 1079, "h": 607}, {"src": "/work/laduree-dubai-hills/03.webp", "thumb": "/work/laduree-dubai-hills/03-sm.webp", "w": 1425, "h": 740}], alt: "Store renovation" },
  { slug: "huda-beauty-kiosk", title: "Huda Beauty retail kiosk", client: "Huda Beauty", category: "retail", service: "interiors", label: "Concept design", where: "Dubai", year: null,
    summary: "A high-impact retail kiosk concept designed for one of the region’s most recognised beauty brands.",
    paragraphs: [
      "A high-impact retail kiosk concept designed for one of the region’s most recognised beauty brands. Built entirely in Huda Beauty’s signature magenta, the kiosk commands attention from every angle oversized balloon orbs, illuminated brand signage and backlit panel displays creating a bold, Instagram-worthy presence on any retail floor.",
      "The counter design prioritises product accessibility with tiered lipstick displays, lit vanity mirrors and dedicated try-on zones, while campaign imagery is integrated directly into the structure. A concept built to stop foot traffic cold."
    ],
    images: [{"src": "/work/huda-beauty-kiosk/01.webp", "thumb": "/work/huda-beauty-kiosk/01-sm.webp", "w": 1425, "h": 800}, {"src": "/work/huda-beauty-kiosk/02.webp", "thumb": "/work/huda-beauty-kiosk/02-sm.webp", "w": 1430, "h": 793}], alt: "Retail kiosk" },
  { slug: "ariel-kiosk", title: "Ariel retail kiosk", client: "Ariel", category: "retail", service: "interiors", label: "Concept design", where: "Dubai", year: null,
    summary: "A supermarket kiosk concept designed for Ariel’s 3-in-1 Pods range.",
    paragraphs: [
      "A supermarket kiosk concept designed for Ariel’s 3-in-1 Pods range. The structure takes the form of an open-canopy booth — a branded roofline in Ariel’s signature green carrying full campaign graphics, with neon-lit interior framing that draws the eye from across the aisle.",
      "Product shelving and display units are built into the structure on all sides, maximising stock visibility while interactive circular dispensing elements at the counter create an engaging touch point for shoppers. Bold product packaging graphics are scaled up across the counter fascia, turning the kiosk itself into a brand statement on the retail floor."
    ],
    images: [{"src": "/work/ariel-kiosk/01.webp", "thumb": "/work/ariel-kiosk/01-sm.webp", "w": 1425, "h": 800}, {"src": "/work/ariel-kiosk/02.webp", "thumb": "/work/ariel-kiosk/02-sm.webp", "w": 1430, "h": 792}], alt: "Retail kiosk" },
  { slug: "roche-riyadh", title: "Roche office", client: "Roche", category: "commercial", service: "interiors", label: "Design consultancy", where: "Riyadh, KSA", year: 2020,
    summary: "A workplace of varied spaces that support different ways of working, from calm and introspective to lively and invigorating.",
    paragraphs: [
      "Roche is a Swiss multinational healthcare company that operates worldwide under two divisions: Pharmaceuticals and Diagnostics. This workplace offers variety of spaces that support different ways of working, employees get tailored work experiences that fits best to their needs.",
      "Apart from the use and size of spaces, another factor contributing to the diversity of this workspace is character. It is formed by mixing different materials, colours, proportions, type and temperature of lighting, furniture type, etc. Depending on the task to be carried out, some spaces have been designed for calm and introspective character, while others, for lively and invigorating."
    ],
    images: [{"src": "/work/roche-riyadh/01.webp", "thumb": "/work/roche-riyadh/01-sm.webp", "w": 600, "h": 339}, {"src": "/work/roche-riyadh/02.webp", "thumb": "/work/roche-riyadh/02-sm.webp", "w": 550, "h": 359}, {"src": "/work/roche-riyadh/03.webp", "thumb": "/work/roche-riyadh/03-sm.webp", "w": 531, "h": 317}, {"src": "/work/roche-riyadh/04.webp", "thumb": "/work/roche-riyadh/04-sm.webp", "w": 562, "h": 416}], alt: "Workplace interior" },
  { slug: "al-hilal-bank-youth-centre", title: "Al Hilal Bank youth banking experience centre", client: "Al Hilal Bank", category: "commercial", service: "interiors", label: "Concept design", where: "Dubai Mall", year: 2021,
    summary: "A concept experience centre that teaches children and teens to understand and manage money through hands-on interaction.",
    paragraphs: [
      "A concept experience centre designed to make banking accessible and engaging for the younger generation teaching children and teens how to understand and manage money through hands-on interaction rather than traditional banking formats. The space moved away from conventional branch design entirely, replacing it with warm timber, living green walls, soft curved forms and vibrant digital installations.",
      "A large video wall served as the centrepiece, displaying dynamic content around financial literacy. An ATM was integrated into the journey alongside a private lounge, interactive zones where younger visitors could engage with banking concepts physically, and a “Press Start” gaming-inspired touchpoint that framed finance as something to explore rather than fear.",
      "The project was halted following the merger between Al Hilal Bank and ADCB but the concept remains one of Nasheman’s most forward-thinking spatial ideas."
    ],
    images: [{"src": "/work/al-hilal-bank-youth-centre/01.webp", "thumb": "/work/al-hilal-bank-youth-centre/01-sm.webp", "w": 1336, "h": 924}, {"src": "/work/al-hilal-bank-youth-centre/02.webp", "thumb": "/work/al-hilal-bank-youth-centre/02-sm.webp", "w": 1425, "h": 964}, {"src": "/work/al-hilal-bank-youth-centre/03.webp", "thumb": "/work/al-hilal-bank-youth-centre/03-sm.webp", "w": 1425, "h": 629}, {"src": "/work/al-hilal-bank-youth-centre/04.webp", "thumb": "/work/al-hilal-bank-youth-centre/04-sm.webp", "w": 853, "h": 573}], alt: "Experience centre concept" },
  { slug: "transmed-dubai-hills", title: "Transmed office", client: "Transmed", category: "commercial", service: "interiors", label: "Design consultancy", where: "Dubai Hills", year: 2021,
    summary: "An office designed to nurture and support the varied products and brands that live within it.",
    paragraphs: [
      "Transmed is a full service distributor, managing and controlling the entire distribution value chain. Transmed focused on the distribution of a very extensive range of Household and Personal Care Products from Procter & Gamble and Clorox, and in parallel developed the distribution of Food products.",
      "Every aspect related to the project is designed with utmost precision. Our concept was driven by the idea of creating an environment that would nurture and support the varied products and brands that exists within this office, allowing the fusion of diverse activities."
    ],
    images: [{"src": "/work/transmed-dubai-hills/01.webp", "thumb": "/work/transmed-dubai-hills/01-sm.webp", "w": 374, "h": 349}, {"src": "/work/transmed-dubai-hills/02.webp", "thumb": "/work/transmed-dubai-hills/02-sm.webp", "w": 509, "h": 347}, {"src": "/work/transmed-dubai-hills/03.webp", "thumb": "/work/transmed-dubai-hills/03-sm.webp", "w": 587, "h": 323}, {"src": "/work/transmed-dubai-hills/04.webp", "thumb": "/work/transmed-dubai-hills/04-sm.webp", "w": 669, "h": 350}], alt: "Office interior" },
  { slug: "golf-estate-villa", title: "Golf Estate villa", client: "", category: "residential", service: "interiors", label: "", where: "Dubai", year: null,
    summary: "A villa interior of metallic tones, marble and black-and-white stone accents.",
    paragraphs: [
      "Decorating with metallic tones has never been so much fun but with modern glam décor. A stunning marble bar counter top injects a monolithic moment of glamour into the heart of the lounge, with sweeping swathes of golden veins in the back of the bar unit. A marble backsplash gracefully links the wall with the other deluxe black and white stone accents in the space.",
      "The marble console is paired with a designer lounge sofa, making it a stylish reading area next to another custom-made full height shelving unit design. Recessed lighting softly highlights the narrow tower. The open layout places the dining area within a metre of the lounge, but the delicately light and airy decor scheme maintains a spacious and uncluttered feel."
    ],
    images: [{"src": "/work/golf-estate-villa/01.webp", "thumb": "/work/golf-estate-villa/01-sm.webp", "w": 540, "h": 275}, {"src": "/work/golf-estate-villa/02.webp", "thumb": "/work/golf-estate-villa/02-sm.webp", "w": 934, "h": 948}, {"src": "/work/golf-estate-villa/03.webp", "thumb": "/work/golf-estate-villa/03-sm.webp", "w": 540, "h": 313}, {"src": "/work/golf-estate-villa/04.webp", "thumb": "/work/golf-estate-villa/04-sm.webp", "w": 509, "h": 588}], alt: "Villa interior" },
  { slug: "dt1-downtown", title: "DT1 residences", client: "", category: "residential", service: "interiors", label: "Design consultancy", where: "Dubai Downtown", year: 2020,
    summary: "Residences in a raw, neutral palette of concrete, corten steel and wood.",
    paragraphs: [
      "The interiors of the project feature different elements with a mix of concrete, corten steel and wood. The colour palette is very neutral and raw, evoking a sense of modern sophistication that is on a more human scale. Driven by today’s modern living style, each residence is designed with plenty of storage spaces for efficiency and convenience.",
      "The open plan kitchens feature integrated high-end appliances, hanging rails, durable and scratch-free countertops and touch technology mixers."
    ],
    images: [{"src": "/work/dt1-downtown/01.webp", "thumb": "/work/dt1-downtown/01-sm.webp", "w": 520, "h": 400}, {"src": "/work/dt1-downtown/02.webp", "thumb": "/work/dt1-downtown/02-sm.webp", "w": 416, "h": 300}, {"src": "/work/dt1-downtown/03.webp", "thumb": "/work/dt1-downtown/03-sm.webp", "w": 336, "h": 161}, {"src": "/work/dt1-downtown/04.webp", "thumb": "/work/dt1-downtown/04-sm.webp", "w": 680, "h": 374}], alt: "Residence interior" },
  { slug: "downtown-design-fair-cafe", title: "Downtown Design entrance way and fair café", client: "Downtown Design", category: "food-and-beverage", service: "interiors", label: "Design consultancy", where: "Dubai", year: 2019,
    summary: "The heart of the café is a tiered high bench layered with landscaping.",
    paragraphs: [
      "The heart of the café is a tiered high bench layered with landscaping. The sculptural focal point was also a place for guests and exhibitors to catch up on work or grab a quick bite. Outside, the terrace area featured an open fire, lush greens and raking sand. the fair’s section for limited-edition and bespoke design marked by a screen of bamboo trees, that whilst doubling as a soft divide from the bustling exhibition space brings nature into the fair’s built environment."
    ],
    images: [{"src": "/work/downtown-design-fair-cafe/01.webp", "thumb": "/work/downtown-design-fair-cafe/01-sm.webp", "w": 517, "h": 449}, {"src": "/work/downtown-design-fair-cafe/02.webp", "thumb": "/work/downtown-design-fair-cafe/02-sm.webp", "w": 414, "h": 277}, {"src": "/work/downtown-design-fair-cafe/03.webp", "thumb": "/work/downtown-design-fair-cafe/03-sm.webp", "w": 512, "h": 288}, {"src": "/work/downtown-design-fair-cafe/04.webp", "thumb": "/work/downtown-design-fair-cafe/04-sm.webp", "w": 480, "h": 316}, {"src": "/work/downtown-design-fair-cafe/05.webp", "thumb": "/work/downtown-design-fair-cafe/05-sm.webp", "w": 815, "h": 897}], alt: "Fair café" },
  { slug: "hitchki-mirdif", title: "Hitchki", client: "Hitchki", category: "food-and-beverage", service: "interiors", label: "Built", where: "Mirdif City Centre, Dubai", year: 2019,
    summary: "An Indian fusion restaurant designed to evoke the nostalgia of a well-travelled home.",
    paragraphs: [
      "Hitchki: A nostalgic sense of home abounds in this Indian fusion restaurant. Designed to provoke a sense of nostalgia within the cosy comforts of “home”, this Indian fusion restaurant mixes old-world charm with modern flair in Dubai. Beyond the warm glow of the bar, the restaurant draws you into the comfy, eclectic “home” of a well-travelled Indian, a purveyor of vintage finds collected from all over the world, artfully displayed on old-fashioned “drawing room” shelves and modern marble and brass side tables.",
      "Mixed with vintage pieces like gramophones and old telephones, perhaps handed down from older generations, there is a sense of nostalgia and a yearning for the simpler, bygone days of communication and entertainment before the digital boom."
    ],
    images: [{"src": "/work/hitchki-mirdif/01.webp", "thumb": "/work/hitchki-mirdif/01-sm.webp", "w": 795, "h": 446}, {"src": "/work/hitchki-mirdif/02.webp", "thumb": "/work/hitchki-mirdif/02-sm.webp", "w": 500, "h": 314}, {"src": "/work/hitchki-mirdif/03.webp", "thumb": "/work/hitchki-mirdif/03-sm.webp", "w": 498, "h": 224}, {"src": "/work/hitchki-mirdif/04.webp", "thumb": "/work/hitchki-mirdif/04-sm.webp", "w": 901, "h": 446}], alt: "Restaurant interior" },
  { slug: "wandr-jlt", title: "Wandr", client: "Eatopia Global", category: "food-and-beverage", service: "interiors", label: "Design consultancy", where: "JLT, Dubai", year: 2024,
    summary: "A wholesome eatery that fuses contemporary elegance with industrial character.",
    paragraphs: [
      "Wandr presents a thoughtfully curated space that fuses contemporary elegance with industrial character, creating an environment that is both stylish and welcoming. The dining area is anchored by smooth terrazzo tables, softly illuminated by cascading pendant lights that add warmth and texture to the ambiance.",
      "Rich red chairs introduce a vibrant contrast, while thoughtfully designed corner seating areas offer a sense of intimacy and relaxation, encouraging guests to stay and savor their meals. The walls are brought to life with expressive artwork that celebrates the values of wholesome nourishment, reinforcing Wandr’s core mission to nurture both the body and the spirit.",
      "Every design element within the space reflects a conscious effort to promote a lifestyle rooted in health, community, and well-being. The bold red signage acts as a confident beacon, while lush green accents throughout the space subtly echo the brand’s commitment to freshness and nature."
    ],
    images: [{"src": "/work/wandr-jlt/01.webp", "thumb": "/work/wandr-jlt/01-sm.webp", "w": 350, "h": 201}, {"src": "/work/wandr-jlt/02.webp", "thumb": "/work/wandr-jlt/02-sm.webp", "w": 350, "h": 234}, {"src": "/work/wandr-jlt/03.webp", "thumb": "/work/wandr-jlt/03-sm.webp", "w": 350, "h": 227}, {"src": "/work/wandr-jlt/04.webp", "thumb": "/work/wandr-jlt/04-sm.webp", "w": 304, "h": 263}, {"src": "/work/wandr-jlt/05.webp", "thumb": "/work/wandr-jlt/05-sm.webp", "w": 346, "h": 263}], alt: "Wholesome eatery" },
];

export const projectBySlug = (slug: string) => PORTFOLIO.find((p) => p.slug === slug);
export const projectsForService = (s: ServiceSlug) => PORTFOLIO.filter((p) => p.service === s);
export const categoryName = (c: Category) => CATEGORIES.find((x) => x.id === c)?.name ?? c;
